### ISSUE TITLE
Crash: item_transport.lua:266: attempt to call field 'register_mvps_unmov'

### ISSUE THREAD

**Issue by fireglow** [VanessaE/pipeworks#100]
Server crash at startup:
```
ERROR[main]: ========== ERROR FROM LUA ===========
ERROR[main]: Failed to load and run script from 
ERROR[main]: /srv/minetest/world/worldmods/pipeworks/init.lua:
ERROR[main]: /srv/minetest/world/worldmods/pipeworks/item_transport.lua:266: attempt to call field 'register_mvps_unmov' (a nil value)
ERROR[main]: stack traceback:
ERROR[main]:        /srv/minetest/world/worldmods/pipeworks/item_transport.lua:266: in main chunk
ERROR[main]:        [C]: in function 'dofile'
ERROR[main]:        /srv/minetest/world/worldmods/pipeworks/init.lua:115: in main chunk
```
I guess this has to do with the recent mesecons changes,
the server starts up fine with pipeworks enabled, but mesecons disabled.

**Comment by VanessaE** [comment]
The issue is in your Mesecons install, not Pipeworks.  Probably your Mesecons install isn't as up-to-date as you think, or you're just missing some components.

That function is defined in mesecons_mvps/init.lua at line 23 and is called by Mesecons' movestones, pistons, and of course Pipeworks uses it too.

Make sure you have the "mesecons_mvps" component of Mesecons installed and enabled.

**Comment by fireglow** [comment]
At the time of the report (05:25 CET), this problem was very real,
Jeija authored a fix at 14:27 CET:
https://github.com/Jeija/minetest-mod-mesecons/commit/eb416475cc511ebfa91d287f911afa9d66162199

**Comment by VanessaE** [comment]
Interesting!  I was not aware that it had even been removed.
